title: nilson's just the docs test
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  external link: https://nilson.itch.io/

# Color scheme supports "light" (default) and "dark"
color_scheme: nilson_color
